language: node_js
node_js:
- stable
branches:
  except:
  - feature
  - bugfix
  only:
  - master
  - stable
deploy:
  provider: heroku
  api_key:
    secure: C8vj+2ncsFyOBBaRgUCxH6cqXhkJmlfzUHfbbW1OW8rYrS/TyzEaOu/T5fSoYspVGwuTs5TEjZEFCi86leeZS0lfL0nwtldc4K4oDymGuVHC3ZlDmw9Is4BT6Svus5sqzqOdAqoJBV77ZsgBYXFcqTXouFH4XjuinhMmjYvEcEPswWj4APOZMUz83eacByIZouNWPCd209ylDe1s2O+kGCR1prCtqYNv2BQIksCFTII7WSSDpYFGgwvzFB560O+oINNbMEzbKFZwBe2RlmXQydibnRiJosZKcsEMJvCeYfsTgh7vNs3JMtS4Mazr1zamBWXLdtenq7k83ER6JgWdNeRJy4/nM51f4I16Ve42pYqeIw+S+3OsXrRW2nQaZoG4gosWKdl1BIV8Y5r1Rp/W34q3VH6z54Ztka4F6PtdadK1h2dsAtviJa+SeIVDz9tAADplr6D4WL0pIoSD7WtLhEqm85aeawsQE/TIFt0pQQoRySg090hqo1XP0DOnukG4LKEsb3liMfIXXNYnNG+30yWj8LA6ZbD6CfreerZPruT12oY6D271x1H9Ac5Xo4XbjjxllObeHSNym21ifXf8qaRkNnF9APKL4HCwGClKx8c/jcvbVa4U4GBhKUa1UEMVaZKfkDSt1YPW+RXfqkvWo/MT3SRL9TJ0gvTU9CHnPFw=
  app: limitless-wave-54219
  on:
    repo: RichardPoulson/gatsby-travis-heroku
  skip_cleanup: 'true'
