language: node_js
node_js:
- stable
branches:
  except:
  - feature
  - bugfix
  only:
  - master
  - stable
deploy:
  provider: heroku
  api_key:
    secure: nBw8lQa/ZGIx1++nhavC0l+1X8rnRhMn3g9QH4YcsYJDHdMPgjf3Mg/JL0vd8MqbMoi6MhTvNxiacDilwGuzWnsuaBATuLgPGDepFk0KcQ+jFu6KoN/8hYQmgRPgxQ7fXsbhFaxgQXVTawWwSkrLG8mdAxqbhjb8xxME7yvlmZ+JEd5RPGMb/ks8ck5ezDqGzrQy/lstrXwPDg/ou/MoRFPw8h8ItTIOWNt/akE0+yxIcqvfqbZbIvp6MFWCsh+enbWChW0CR2LD2s9MxlAAwgl1jHClavLywUDAqA1vJUzEhLizu3V3Bw6hj6y+DCZTYy1iyTVsuq3n2V/zJ9z5DXib4bpjyG39vvAoH3N2gcNHBBSAWhn0H4uyK04EUSA9uxPt72FwJdHrUSuPm64jebc0+jEipMr0n+dWt/Bo73zIO2A8ueK2H0aLeVuhLC8nq/3rEwo2aOblYmglXsmc1MCTlxK1y6HHHSTweAml4fZH+LQxOr7ZEDpBblBPAX/nDd10TEWIj2Vhzwrk3ryHyPfvC0//hOZ4FTSWvi+9zahCjjsKrMAXlaLwsfxUfBUDvyvHZabGP7pSsgPfDQysrPh3bY68B0PkAKAdtFFI+PJVfm2Vil77qGdsrsmoMFWEbZLI5KOGaArV7vYXj+VpEZYWSoaLM69DOVceXthPJoE=
  app: limitless-wave-54219
  on:
    repo: RichardPoulson/gatsby-travis-heroku
  skip_cleanup: 'true'
