language: node_js
node_js:
- stable
branches:
  except:
  - feature
  - bugfix
  only:
  - master
  - stable
deploy:
  provider: heroku
  api_key:
    secure: VqFjJBJWjWHvQoD0pUxCKlo0X7a1IEZXf2tdBDRhD19n8/PlwTr4teiW7kGZ2rAIIcdY3mjhY0If518AmbmyW1JnAJIanSk4onDZyw1xuwOCm3y7NcNnz9pWUZm6fl1HeyLOfnas5Q4pi+lk1Qe/xxMJNGPfmEZjtk/kBqHIAcEdGuN1zubMxJsQvKWo5VAiGYwSnx8Zqev62Ke8Ufl0wyUp3EuQbSlYZHimkns+oY8hHg0Ay21b9wJ+YoUALeEFYKern+maLmITMXjiqPmSxDzN6pFh1nNocjEV4324skdfm12HTht5eidVenqE7eM9rZB/vVlbmp8MQbk01el4d/1s0o2OCAiLM+q7u3aolw9W0DxSoXVjs6c4u857HadP1oxo0I5ZM/pzSJ3vTfOs4Nqu0IBjK6YEL5aE8LHeX10v4skWDEtURGPCU4aGVLD7P0y/ACM/QVCHLXUCuhlTbVW8RQX+82ClPaPq2MVmvmYdrmx4GN8x5aK27YW+oNL03L5TBg4Jr5epQ8lM7w/yATo45YuobEshtRhF7U+ewOxvVQHwA+G7mHdjPzQi7TRw+W4wCFN8UW5tVP3oJNjzwx988iMd1QsrlbgR6gOgXwdfJUM7NhePw6S/+vUJFYaLZ4PJqnlxZdnm5mg9Ve93xH8QUnYqqbg/2evzB2kliS4=
  app: limitless-wave-54219
  on:
    repo: RichardPoulson/gatsby-travis-heroku
  skip_cleanup: 'true'
